name: pro_media_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.3.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  injectable_generator: ^2.4.1
  freezed_annotation: ^2.4.1
  intl:
  animated_text_kit:
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg:
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/

